# Generated by Django 3.0.4 on 2020-05-08 11:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ImageField(upload_to='user_profile')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=100)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None)),
                ('address', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=50)),
                ('specialisation', models.CharField(max_length=50)),
                ('current_year', models.CharField(max_length=50)),
                ('institution_name', models.CharField(max_length=100)),
                ('institution_address', models.CharField(max_length=200)),
                ('career_category', models.CharField(max_length=50)),
                ('career_specification', models.CharField(max_length=50)),
            ],
        ),
    ]
