# Generated by Django 3.0 on 2020-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_user_id', models.IntegerField()),
                ('user_role', models.CharField(max_length=255)),
                ('role_user_name', models.CharField(max_length=255)),
                ('role_user_email', models.CharField(max_length=255)),
                ('role_user_password', models.CharField(max_length=255)),
            ],
        ),
    ]
