# Generated by Django 3.0 on 2020-05-07 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_roledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledetails',
            name='role_create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
