# Generated by Django 3.0.6 on 2020-05-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
