# Generated by Django 3.0.6 on 2020-05-09 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_user_id', models.CharField(max_length=10)),
                ('user_role', models.CharField(max_length=255)),
                ('role_user_name', models.CharField(max_length=255)),
                ('role_user_email', models.CharField(max_length=255)),
                ('role_user_password', models.CharField(max_length=255)),
                ('role_create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
