# Generated by Django 3.0 on 2020-05-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_roledetails_role_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleDetails',
            new_name='RoleDetail',
        ),
    ]
