# Generated by Django 3.0 on 2020-05-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20200507_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledetail',
            name='role_user_id',
            field=models.CharField(max_length=10),
        ),
    ]
