# Generated by Django 3.0.6 on 2020-05-10 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0007_roledetail_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('IT', 'IT & Software'), ('bus', 'Business & Startups'), ('des', 'Designs'), ('ele', 'Electronics & Electricals')], default='IT', max_length=3)),
                ('difficulty_level', models.CharField(blank=True, choices=[('begin', 'Beginner'), ('inter', 'Intermediate'), ('adv', 'Advanced')], max_length=6, null=True)),
                ('lesson_title', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('requirements', models.CharField(blank=True, max_length=100, null=True)),
                ('learn', models.CharField(blank=True, max_length=100, null=True)),
                ('course_points', models.IntegerField(default=0)),
                ('certificate', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
