# Generated by Django 3.0.6 on 2020-05-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'IT & Software'), ('bus', 'Business & Startups'), ('des', 'Designs'), ('ele', 'Electronics & Electricals')], max_length=3, null=True),
        ),
    ]
