# Generated by Django 3.0.6 on 2020-05-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_auto_20200510_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'IT & Software'), ('business', 'Business & Startups'), ('design', 'Designs'), ('ele', 'Electronics & Electricals')], max_length=10, null=True),
        ),
    ]
